import { describe, expect, it } from 'vitest'
import { ANSI_COLORS, parseAnsiForVue, parseAnsiToHtml } from '../ansiParser'

/*
 * MUD color codes map to fixed Tailwind classes: they are game semantics, not
 * theme. These pins fail if a palette sweep or token change alters them.
 */
const SAMPLE =
  '&+Rred &+ggreen &+Yyellow &+bblue &+Mmagenta &+ccyan &+Wwhite &+Lgray &=rWalert&n plain'

describe('ANSI color classes are pinned', () => {
  it('keeps every color code mapped to its original class', () => {
    expect(
      Object.fromEntries(ANSI_COLORS.map((color) => [color.code, color.class])),
    ).toMatchInlineSnapshot(`
      {
        "&+*": "text-white font-bold animate-pulse",
        "&+B": "text-blue-400 font-bold",
        "&+C": "text-cyan-300 font-bold",
        "&+G": "text-green-400 font-bold",
        "&+L": "text-gray-500 font-bold",
        "&+M": "text-purple-400 font-bold",
        "&+R": "text-red-400 font-bold",
        "&+W": "text-white font-bold",
        "&+Y": "text-yellow-300 font-bold",
        "&+b": "text-blue-600",
        "&+c": "text-cyan-600",
        "&+d": "font-bold",
        "&+f": "animate-pulse",
        "&+g": "text-green-600",
        "&+i": "italic",
        "&+l": "text-gray-400",
        "&+m": "text-purple-600",
        "&+r": "text-red-600",
        "&+u": "underline",
        "&+w": "text-gray-400",
        "&+y": "text-yellow-600",
        "&-B": "bg-blue-800",
        "&-C": "bg-cyan-800",
        "&-G": "bg-green-800",
        "&-L": "bg-gray-800",
        "&-M": "bg-purple-800",
        "&-R": "bg-red-800",
        "&-W": "bg-white",
        "&-Y": "bg-yellow-700",
        "&-b": "bg-blue-900",
        "&-c": "bg-cyan-900",
        "&-g": "bg-green-900",
        "&-l": "bg-black",
        "&-m": "bg-purple-900",
        "&-r": "bg-red-900",
        "&-w": "bg-gray-400",
        "&-y": "bg-yellow-900",
        "&=BB": "bg-blue-800 text-blue-400 font-bold",
        "&=BC": "bg-blue-800 text-cyan-300 font-bold",
        "&=BG": "bg-blue-800 text-green-400 font-bold",
        "&=BL": "bg-blue-800 text-gray-500 font-bold",
        "&=BM": "bg-blue-800 text-purple-400 font-bold",
        "&=BR": "bg-blue-800 text-red-400 font-bold",
        "&=BW": "bg-blue-800 text-white font-bold",
        "&=BY": "bg-blue-800 text-yellow-300 font-bold",
        "&=Bb": "bg-blue-800 text-blue-600",
        "&=Bc": "bg-blue-800 text-cyan-600",
        "&=Bg": "bg-blue-800 text-green-600",
        "&=Bl": "bg-blue-800 text-gray-400",
        "&=Bm": "bg-blue-800 text-purple-600",
        "&=Br": "bg-blue-800 text-red-600",
        "&=Bw": "bg-blue-800 text-gray-400",
        "&=By": "bg-blue-800 text-yellow-600",
        "&=CB": "bg-cyan-800 text-blue-400 font-bold",
        "&=CC": "bg-cyan-800 text-cyan-300 font-bold",
        "&=CG": "bg-cyan-800 text-green-400 font-bold",
        "&=CL": "bg-cyan-800 text-gray-500 font-bold",
        "&=CM": "bg-cyan-800 text-purple-400 font-bold",
        "&=CR": "bg-cyan-800 text-red-400 font-bold",
        "&=CW": "bg-cyan-800 text-white font-bold",
        "&=CY": "bg-cyan-800 text-yellow-300 font-bold",
        "&=Cb": "bg-cyan-800 text-blue-600",
        "&=Cc": "bg-cyan-800 text-cyan-600",
        "&=Cg": "bg-cyan-800 text-green-600",
        "&=Cl": "bg-cyan-800 text-gray-400",
        "&=Cm": "bg-cyan-800 text-purple-600",
        "&=Cr": "bg-cyan-800 text-red-600",
        "&=Cw": "bg-cyan-800 text-gray-400",
        "&=Cy": "bg-cyan-800 text-yellow-600",
        "&=GB": "bg-green-800 text-blue-400 font-bold",
        "&=GC": "bg-green-800 text-cyan-300 font-bold",
        "&=GG": "bg-green-800 text-green-400 font-bold",
        "&=GL": "bg-green-800 text-gray-500 font-bold",
        "&=GM": "bg-green-800 text-purple-400 font-bold",
        "&=GR": "bg-green-800 text-red-400 font-bold",
        "&=GW": "bg-green-800 text-white font-bold",
        "&=GY": "bg-green-800 text-yellow-300 font-bold",
        "&=Gb": "bg-green-800 text-blue-600",
        "&=Gc": "bg-green-800 text-cyan-600",
        "&=Gg": "bg-green-800 text-green-600",
        "&=Gl": "bg-green-800 text-gray-400",
        "&=Gm": "bg-green-800 text-purple-600",
        "&=Gr": "bg-green-800 text-red-600",
        "&=Gw": "bg-green-800 text-gray-400",
        "&=Gy": "bg-green-800 text-yellow-600",
        "&=LB": "bg-gray-800 text-blue-400 font-bold",
        "&=LC": "bg-gray-800 text-cyan-300 font-bold",
        "&=LG": "bg-gray-800 text-green-400 font-bold",
        "&=LL": "bg-gray-800 text-gray-500 font-bold",
        "&=LM": "bg-gray-800 text-purple-400 font-bold",
        "&=LR": "bg-gray-800 text-red-400 font-bold",
        "&=LW": "bg-gray-800 text-white font-bold",
        "&=LY": "bg-gray-800 text-yellow-300 font-bold",
        "&=Lb": "bg-gray-800 text-blue-600",
        "&=Lc": "bg-gray-800 text-cyan-600",
        "&=Lg": "bg-gray-800 text-green-600",
        "&=Ll": "bg-gray-800 text-gray-400",
        "&=Lm": "bg-gray-800 text-purple-600",
        "&=Lr": "bg-gray-800 text-red-600",
        "&=Lw": "bg-gray-800 text-gray-400",
        "&=Ly": "bg-gray-800 text-yellow-600",
        "&=MB": "bg-purple-800 text-blue-400 font-bold",
        "&=MC": "bg-purple-800 text-cyan-300 font-bold",
        "&=MG": "bg-purple-800 text-green-400 font-bold",
        "&=ML": "bg-purple-800 text-gray-500 font-bold",
        "&=MM": "bg-purple-800 text-purple-400 font-bold",
        "&=MR": "bg-purple-800 text-red-400 font-bold",
        "&=MW": "bg-purple-800 text-white font-bold",
        "&=MY": "bg-purple-800 text-yellow-300 font-bold",
        "&=Mb": "bg-purple-800 text-blue-600",
        "&=Mc": "bg-purple-800 text-cyan-600",
        "&=Mg": "bg-purple-800 text-green-600",
        "&=Ml": "bg-purple-800 text-gray-400",
        "&=Mm": "bg-purple-800 text-purple-600",
        "&=Mr": "bg-purple-800 text-red-600",
        "&=Mw": "bg-purple-800 text-gray-400",
        "&=My": "bg-purple-800 text-yellow-600",
        "&=RB": "bg-red-800 text-blue-400 font-bold",
        "&=RC": "bg-red-800 text-cyan-300 font-bold",
        "&=RG": "bg-red-800 text-green-400 font-bold",
        "&=RL": "bg-red-800 text-gray-500 font-bold",
        "&=RM": "bg-red-800 text-purple-400 font-bold",
        "&=RR": "bg-red-800 text-red-400 font-bold",
        "&=RW": "bg-red-800 text-white font-bold",
        "&=RY": "bg-red-800 text-yellow-300 font-bold",
        "&=Rb": "bg-red-800 text-blue-600",
        "&=Rc": "bg-red-800 text-cyan-600",
        "&=Rg": "bg-red-800 text-green-600",
        "&=Rl": "bg-red-800 text-gray-400",
        "&=Rm": "bg-red-800 text-purple-600",
        "&=Rr": "bg-red-800 text-red-600",
        "&=Rw": "bg-red-800 text-gray-400",
        "&=Ry": "bg-red-800 text-yellow-600",
        "&=WB": "bg-white text-blue-400 font-bold",
        "&=WC": "bg-white text-cyan-300 font-bold",
        "&=WG": "bg-white text-green-400 font-bold",
        "&=WL": "bg-white text-gray-500 font-bold",
        "&=WM": "bg-white text-purple-400 font-bold",
        "&=WR": "bg-white text-red-400 font-bold",
        "&=WW": "bg-white text-white font-bold",
        "&=WY": "bg-white text-yellow-300 font-bold",
        "&=Wb": "bg-white text-blue-600",
        "&=Wc": "bg-white text-cyan-600",
        "&=Wg": "bg-white text-green-600",
        "&=Wl": "bg-white text-gray-400",
        "&=Wm": "bg-white text-purple-600",
        "&=Wr": "bg-white text-red-600",
        "&=Ww": "bg-white text-gray-400",
        "&=Wy": "bg-white text-yellow-600",
        "&=YB": "bg-yellow-700 text-blue-400 font-bold",
        "&=YC": "bg-yellow-700 text-cyan-300 font-bold",
        "&=YG": "bg-yellow-700 text-green-400 font-bold",
        "&=YL": "bg-yellow-700 text-gray-500 font-bold",
        "&=YM": "bg-yellow-700 text-purple-400 font-bold",
        "&=YR": "bg-yellow-700 text-red-400 font-bold",
        "&=YW": "bg-yellow-700 text-white font-bold",
        "&=YY": "bg-yellow-700 text-yellow-300 font-bold",
        "&=Yb": "bg-yellow-700 text-blue-600",
        "&=Yc": "bg-yellow-700 text-cyan-600",
        "&=Yg": "bg-yellow-700 text-green-600",
        "&=Yl": "bg-yellow-700 text-gray-400",
        "&=Ym": "bg-yellow-700 text-purple-600",
        "&=Yr": "bg-yellow-700 text-red-600",
        "&=Yw": "bg-yellow-700 text-gray-400",
        "&=Yy": "bg-yellow-700 text-yellow-600",
        "&=bB": "bg-blue-900 text-blue-400 font-bold",
        "&=bC": "bg-blue-900 text-cyan-300 font-bold",
        "&=bG": "bg-blue-900 text-green-400 font-bold",
        "&=bL": "bg-blue-900 text-gray-500 font-bold",
        "&=bM": "bg-blue-900 text-purple-400 font-bold",
        "&=bR": "bg-blue-900 text-red-400 font-bold",
        "&=bW": "bg-blue-900 text-white font-bold",
        "&=bY": "bg-blue-900 text-yellow-300 font-bold",
        "&=bb": "bg-blue-900 text-blue-600",
        "&=bc": "bg-blue-900 text-cyan-600",
        "&=bg": "bg-blue-900 text-green-600",
        "&=bl": "bg-blue-900 text-gray-400",
        "&=bm": "bg-blue-900 text-purple-600",
        "&=br": "bg-blue-900 text-red-600",
        "&=bw": "bg-blue-900 text-gray-400",
        "&=by": "bg-blue-900 text-yellow-600",
        "&=cB": "bg-cyan-900 text-blue-400 font-bold",
        "&=cC": "bg-cyan-900 text-cyan-300 font-bold",
        "&=cG": "bg-cyan-900 text-green-400 font-bold",
        "&=cL": "bg-cyan-900 text-gray-500 font-bold",
        "&=cM": "bg-cyan-900 text-purple-400 font-bold",
        "&=cR": "bg-cyan-900 text-red-400 font-bold",
        "&=cW": "bg-cyan-900 text-white font-bold",
        "&=cY": "bg-cyan-900 text-yellow-300 font-bold",
        "&=cb": "bg-cyan-900 text-blue-600",
        "&=cc": "bg-cyan-900 text-cyan-600",
        "&=cg": "bg-cyan-900 text-green-600",
        "&=cl": "bg-cyan-900 text-gray-400",
        "&=cm": "bg-cyan-900 text-purple-600",
        "&=cr": "bg-cyan-900 text-red-600",
        "&=cw": "bg-cyan-900 text-gray-400",
        "&=cy": "bg-cyan-900 text-yellow-600",
        "&=gB": "bg-green-900 text-blue-400 font-bold",
        "&=gC": "bg-green-900 text-cyan-300 font-bold",
        "&=gG": "bg-green-900 text-green-400 font-bold",
        "&=gL": "bg-green-900 text-gray-500 font-bold",
        "&=gM": "bg-green-900 text-purple-400 font-bold",
        "&=gR": "bg-green-900 text-red-400 font-bold",
        "&=gW": "bg-green-900 text-white font-bold",
        "&=gY": "bg-green-900 text-yellow-300 font-bold",
        "&=gb": "bg-green-900 text-blue-600",
        "&=gc": "bg-green-900 text-cyan-600",
        "&=gg": "bg-green-900 text-green-600",
        "&=gl": "bg-green-900 text-gray-400",
        "&=gm": "bg-green-900 text-purple-600",
        "&=gr": "bg-green-900 text-red-600",
        "&=gw": "bg-green-900 text-gray-400",
        "&=gy": "bg-green-900 text-yellow-600",
        "&=lB": "bg-black text-blue-400 font-bold",
        "&=lC": "bg-black text-cyan-300 font-bold",
        "&=lG": "bg-black text-green-400 font-bold",
        "&=lL": "bg-black text-gray-500 font-bold",
        "&=lM": "bg-black text-purple-400 font-bold",
        "&=lR": "bg-black text-red-400 font-bold",
        "&=lW": "bg-black text-white font-bold",
        "&=lY": "bg-black text-yellow-300 font-bold",
        "&=lb": "bg-black text-blue-600",
        "&=lc": "bg-black text-cyan-600",
        "&=lg": "bg-black text-green-600",
        "&=ll": "bg-black text-gray-400",
        "&=lm": "bg-black text-purple-600",
        "&=lr": "bg-black text-red-600",
        "&=lw": "bg-black text-gray-400",
        "&=ly": "bg-black text-yellow-600",
        "&=mB": "bg-purple-900 text-blue-400 font-bold",
        "&=mC": "bg-purple-900 text-cyan-300 font-bold",
        "&=mG": "bg-purple-900 text-green-400 font-bold",
        "&=mL": "bg-purple-900 text-gray-500 font-bold",
        "&=mM": "bg-purple-900 text-purple-400 font-bold",
        "&=mR": "bg-purple-900 text-red-400 font-bold",
        "&=mW": "bg-purple-900 text-white font-bold",
        "&=mY": "bg-purple-900 text-yellow-300 font-bold",
        "&=mb": "bg-purple-900 text-blue-600",
        "&=mc": "bg-purple-900 text-cyan-600",
        "&=mg": "bg-purple-900 text-green-600",
        "&=ml": "bg-purple-900 text-gray-400",
        "&=mm": "bg-purple-900 text-purple-600",
        "&=mr": "bg-purple-900 text-red-600",
        "&=mw": "bg-purple-900 text-gray-400",
        "&=my": "bg-purple-900 text-yellow-600",
        "&=rB": "bg-red-900 text-blue-400 font-bold",
        "&=rC": "bg-red-900 text-cyan-300 font-bold",
        "&=rG": "bg-red-900 text-green-400 font-bold",
        "&=rL": "bg-red-900 text-gray-500 font-bold",
        "&=rM": "bg-red-900 text-purple-400 font-bold",
        "&=rR": "bg-red-900 text-red-400 font-bold",
        "&=rW": "bg-red-900 text-white font-bold",
        "&=rY": "bg-red-900 text-yellow-300 font-bold",
        "&=rb": "bg-red-900 text-blue-600",
        "&=rc": "bg-red-900 text-cyan-600",
        "&=rg": "bg-red-900 text-green-600",
        "&=rl": "bg-red-900 text-gray-400",
        "&=rm": "bg-red-900 text-purple-600",
        "&=rr": "bg-red-900 text-red-600",
        "&=rw": "bg-red-900 text-gray-400",
        "&=ry": "bg-red-900 text-yellow-600",
        "&=wB": "bg-gray-400 text-blue-400 font-bold",
        "&=wC": "bg-gray-400 text-cyan-300 font-bold",
        "&=wG": "bg-gray-400 text-green-400 font-bold",
        "&=wL": "bg-gray-400 text-gray-500 font-bold",
        "&=wM": "bg-gray-400 text-purple-400 font-bold",
        "&=wR": "bg-gray-400 text-red-400 font-bold",
        "&=wW": "bg-gray-400 text-white font-bold",
        "&=wY": "bg-gray-400 text-yellow-300 font-bold",
        "&=wb": "bg-gray-400 text-blue-600",
        "&=wc": "bg-gray-400 text-cyan-600",
        "&=wg": "bg-gray-400 text-green-600",
        "&=wl": "bg-gray-400 text-gray-400",
        "&=wm": "bg-gray-400 text-purple-600",
        "&=wr": "bg-gray-400 text-red-600",
        "&=ww": "bg-gray-400 text-gray-400",
        "&=wy": "bg-gray-400 text-yellow-600",
        "&=yB": "bg-yellow-900 text-blue-400 font-bold",
        "&=yC": "bg-yellow-900 text-cyan-300 font-bold",
        "&=yG": "bg-yellow-900 text-green-400 font-bold",
        "&=yL": "bg-yellow-900 text-gray-500 font-bold",
        "&=yM": "bg-yellow-900 text-purple-400 font-bold",
        "&=yR": "bg-yellow-900 text-red-400 font-bold",
        "&=yW": "bg-yellow-900 text-white font-bold",
        "&=yY": "bg-yellow-900 text-yellow-300 font-bold",
        "&=yb": "bg-yellow-900 text-blue-600",
        "&=yc": "bg-yellow-900 text-cyan-600",
        "&=yg": "bg-yellow-900 text-green-600",
        "&=yl": "bg-yellow-900 text-gray-400",
        "&=ym": "bg-yellow-900 text-purple-600",
        "&=yr": "bg-yellow-900 text-red-600",
        "&=yw": "bg-yellow-900 text-gray-400",
        "&=yy": "bg-yellow-900 text-yellow-600",
        "&N": "text-gray-300",
        "&n": "text-gray-300",
      }
    `)
  })

  it('renders a fixed sample with the original classes', () => {
    expect(parseAnsiToHtml(SAMPLE)).toMatchInlineSnapshot(
      `"<span class="text-red-400 font-bold">red </span><span class="text-green-600">green </span><span class="text-yellow-300 font-bold">yellow </span><span class="text-blue-600">blue </span><span class="text-purple-400 font-bold">magenta </span><span class="text-cyan-600">cyan </span><span class="text-white font-bold">white </span><span class="text-gray-500 font-bold">gray </span><span class="bg-red-900 text-white font-bold">alert</span><span class="text-gray-300"> plain</span>"`,
    )
    expect(parseAnsiForVue(SAMPLE)).toMatchInlineSnapshot(
      `"<span class="text-red-400 font-bold">red </span><span class="text-green-600">green </span><span class="text-yellow-300 font-bold">yellow </span><span class="text-blue-600">blue </span><span class="text-purple-400 font-bold">magenta </span><span class="text-cyan-600">cyan </span><span class="text-white font-bold">white </span><span class="text-gray-500 font-bold">gray </span><span class="bg-red-900 text-white font-bold">alert</span><span class="text-gray-300"> plain</span>"`,
    )
  })
})
