bind @REDIS_BIND_ADDRESS@
protected-mode yes
port @REDIS_PORT@
daemonize no
supervised no
databases @REDIS_DATABASE_COUNT@

dir @REDIS_DATA_DIR@
dbfilename dump.rdb
save ""
appendonly no

maxmemory @REDIS_MAX_MEMORY@
maxmemory-policy allkeys-lru

rename-command FLUSHALL ""
rename-command FLUSHDB ""
logfile ""
